#pragma once


#define SYNTAX_LPAREN '('
#define SYNTAX_RPAREN ')'

#define SYNTAX_FUNC_L '('
#define SYNTAX_FUNC_R ')'
#define SYNTAX_FUNC_PCOND ':'
#define SYNTAX_FUNC_PSEP ','
#define SYNTAX_FUNC_PROLOGUE '='

#define SYNTAX_LIST_L '['
#define SYNTAX_LIST_R ']'
#define SYNTAX_LIST_SEP ','

#define SYNTAX_LAMBDA '@'
#define SYNTAX_LAMBDA_L '{'
#define SYNTAX_LAMBDA_R '}'

#define SYNTAX_LCOMP_SEP '$'
#define SYNTAX_LCOMP_FILTER SYNTAX_FUNC_PCOND
#define SYNTAX_LCOMP_MAP SYNTAX_FUNC_PROLOGUE

#define SYNTAX_WITH_L SYNTAX_FUNC_L
#define SYNTAX_WITH_R SYNTAX_FUNC_R
#define SYNTAX_WITH_ASSIGN SYNTAX_FUNC_PROLOGUE
#define SYNTAX_WITH_SEP SYNTAX_FUNC_PSEP



#define SYNTAX_MINI_LAMBDA_L '`'
#define SYNTAX_MINI_LAMBDA_BIN '&'